version: '2.0'

services:
  redis:
    image: redis
  web:
    build:
      context: ./bender
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - 8383:8888
    environment:
      APP_ENV: 'dev'
      ASYNC: 0
      REDIS_URL: 'redis://redis:6379/1'
    links:
      - redis

  # test:
  #   build:
  #     context: ./bender
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./app:/src
  #   ports:
  #     - 8384:8888
