version: '2.0'

services:
  redis:
    image: redis
  web: &web-base
    build:
      context: ./bender
      dockerfile: Dockerfile
    volumes:
      - ./bender:/app
    ports:
      - 8383:8888
    environment:
      APP_ENV: 'dev'
      ASYNC: 0
      REDIS_URL: 'redis://redis:6379/1'
    links:
      - redis
  test:
    <<: *web-base
    build:
      context: ./bender
      dockerfile: Dockerfile.dev
    ports:
      - 8384:8888
