classification:
  default: &default
    project: BUG
    issuetype: Bug
    component: 911
    priority: P1
    team: ''
  def_infra: &def_infra
    <<: *default
    component: Infrastructure
    team: infra_system_team_tier_1
  def_infra_db: &def_infra_db
    <<: *def_infra
    team: infra_db_team
  def_infra_p2: &def_infra_p2
    <<: *def_infra
    priority: P2
    team: z_infra_auto_alerting
  details:
    - hkbc:
        default:
          <<: *default
          component: CrossBorder
          team: cross_border
    - processor load:
        default: *def_infra
        details:
          - lzdlivees:
              default:
                <<: *default
                component: Vertical - Search
                team: v_Search_backend
    - free disk space:
        default: *def_infra
        details:
          - stg:
              default: *def_infra_p2
          - dbdev:
              default: *def_infra_p2
          - hkdc-srv-01067.lzd.io:
              default: *def_infra_db
          - backup:
              default: *def_infra_db
          - livecas:
              default:
                <<: *default
                team: z_cas_alerting
          - pgpool:
              default: *def_infra_db
          - biliveora:
              default:
                <<: *default
                component: BI
                team: h_bi_oracle
          - bilivegp:
              default:
                <<: *default
                component: BI
                team: h_bi_greenplum
          - lzdlivebi:
              default: *def_infra_db
          - platform:
              default:
                <<: *default
                component: Platform
                team: Performance_testing_team
          - anon:
              default: *def_infra_p2
          - sapstorage:
              default:
                <<: *def_infra
                team: ''
          - lellive:
              default:
                <<: *default
                component: LEL
                team: lel_Release
          - omsliveweb:
              default: &def_oms
                <<: *default
                component: Vertical - Order mgmt & returns
                team: v_OM_Returns_Procurement
              details:
                - volume /data:
                    default: *def_oms
                - volume /:
                    default: *def_infra
          - ops-db-02.lazada.com:
              default:
                <<: *default
                component: Notifications / Tracking
                team: h_Nms
              details:
                - volume /$: *def_infra
          - db:
              default: *def_infra_db
    - mysql:
        default: *def_infra_db
    - connection:
        default: *def_infra_db
    - consumer: &def_rmq
        default: *default
        details:
          - lms:
              default:
                <<: *default
                component: LMS
                team: h_Lms
          - catalog_tax_class:
              default:
                <<: *default
                team: v_ShippingFree
                component: Vertical - ShippingFree
          - orderprocessing.cybersource:
              default: *def_infra
          - oms.stock:
              default: &def_stock_api
                <<: *default
                component: STOCK API
                team: h_GeoAPI_StockAPI_PHPConsumer
          - oms.warehouse:
              default: *def_stock_api
          - product_service:
              default: &def_product_service
                <<: *default
                component: Product Service
                team: h_ProductService_ImageStorage_Notificator_Scapi
          - sellercenter:
              default: *def_product_service
          - scapi:
              default: *def_product_service
          - orderapi:
              default:
                <<: *default
                component: Horizontal - APIs
                team:  h_OrderAPI
          - email_api:
              default:
                <<: *default
                component: Horizontal - APIs
                team: h_CustomerAPI_ConfigAPI
          - bob:
              default: *def_infra
          - alipay:
              default:
                <<: *default
                component: Alipay
                team: z_Alipay_auto_alerts_team
          - distributed:
              default:
                <<: *default
                component: Horizontal - Tracking
                team: ''
          - productfeed:
              default:
                <<: *default
                team: 911_monitoring_team
          - notificator:
              default: *def_product_service
          - orderprocessing:
              default:
                <<: *default
                component: Vertical - Order mgmt & returns
                team: v_OM_Returns_Procurement
          - product_import:
              default: &def_product_import
                <<: *default
                component: Product Import
                team: v_Search_product_import
          - cc:
              default: *def_product_import
          - elasticsearch:
              default: &def_search
                <<: *default
                component: Vertical - Search
                team: v_Search_backend
          - ha3:
              default: *def_search
          - _update:
              default: *def_search
          - oms:
              default: *def_oms
          - homer:
              default: *def_oms
    - queue is having: *def_rmq
    - ack_rate: *def_rmq
    - php-fpm:
        default: *default
        details:
          - oms:
              default: *def_oms
    - postgresql:
        default: *def_infra_db
    - puppet:
        default: *def_infra_p2
    - sybase:
        default: *def_infra_db
    - zabbix agent:
        default: *def_infra_p2
    - 10g:
        default: *def_infra
    - ilo:
        default: *def_infra_p2
    - icmp:
        default: *def_infra
        details:
          - stg:
              default: *def_infra_p2
          - dbdev:
              default: *def_infra_p2
    - memory:
        default: *def_infra
        details:
          - anon:
              default: *def_infra_p2
          - c360liveautostatsapp:
              default:
                <<: *default
                component: BI
                team: h_bi
          - hkdc-srv-01067.lzd.io:
              default: *def_infra_db
          - platform:
              default:
                <<: *default
                team: Performance_testing_team
                component: Platform
          - db:
              default: *def_infra_db
    - alice health:
        default: *def_infra
    - replication:
        default: *def_infra_db
    - slave:
        default: *def_infra_db
    - slow queries:
        default: *def_infra_db
    - dead rabbit:
        default: *def_infra
    - backup:
        default: *def_infra_db
    - cpu:
        default: *def_infra
    - inode:
        default: *def_infra
        details:
          - db:
              default: *def_infra_db
    - jsagent:
        default: *def_infra
    - packagist:
        default: *default
    - pgpool:
        default: *def_infra_db
    - processes:
        default: *def_infra
        details:
          - db:
              default: *def_infra_db
    - rsyslog:
        default: *def_infra
    - walsreceiver:
        default: *def_infra_db
    - es cluster:
        default: *def_infra
    - docker daemon:
        default: *def_infra
    - could not connect:
        default: *def_infra_p2
    - not reachable:
        default: *def_infra
        details:
          - jenkins:
              default: *def_infra_p2
    - zabbixdb:
        default: *def_infra
