FROM newbenderrodriguez_web:latest
RUN pip install -r requirements.dev.txt
ADD . /app
ADD supervisord.conf /etc/supervisord.conf
WORKDIR /app
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
